/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baccarat.ui;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author filme
 */
public class ImageView extends javax.swing.JPanel {

    /**
     * Creates new form ImageView
     */
    private int x = 0;
    private String urlImage = "/baccarat/imagem/";

    public ImageView() {
        initComponents();

        Timer tm = new Timer(900, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                File[] ficheiros = getFicheiro();
                for (File f : ficheiros) {

                    ImageIcon icon = new ImageIcon(f.getAbsolutePath());

                    Image image = icon.getImage().getScaledInstance(lbSlide.getWidth(), lbSlide.getHeight(), Image.SCALE_SMOOTH);
                    lbSlide.setIcon(new ImageIcon(image));
                    x += 1;
                    if (x >= ficheiros.length) {
                        x = 0;
                    }

                }
            }
        });
        tm.start();
    }

 

    private File[] getFicheiro() {

        File folder = new File("imagem/slide/");
        return folder.listFiles();

    }

    public String[] getImages() {
        File file = new File(getClass().getResource(urlImage).getFile());
        String[] imagesList = file.list();
        return imagesList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSlide = new javax.swing.JLabel();

        lbSlide.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbSlide.setForeground(new java.awt.Color(204, 204, 204));
        lbSlide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSlide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baccarat/icons/logo-novo.png"))); // NOI18N
        lbSlide.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSlide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSlide)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbSlide;
    // End of variables declaration//GEN-END:variables
}
