/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baccarat.ui;

import ao.co.proevolution.baccarat.model.Aposta;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author Rufino Domingos
 */
public class menuJogoView extends javax.swing.JDialog {

    /**
     * Creates new form painelConfiguracao
     */
    private Aposta _aposta;
    private java.awt.Frame parent ;

    public menuJogoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.iconeSistema();
        this.parent = parent;

    }

    public menuJogoView(java.awt.Frame parent, boolean modal, Aposta aposta) {
        super(parent, modal);
        initComponents();
        this.iconeSistema();
        this._aposta = aposta;
        this.parent = parent;
    }

    public void iconeSistema() {
        URL caminho = this.getClass().getResource("icon.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminho);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblApostador = new javax.swing.JLabel();
        lblConfigJogo = new javax.swing.JLabel();
        lblConfigJogo1 = new javax.swing.JLabel();
        lblApostador1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Painel de Configurações");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblApostador.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblApostador.setForeground(new java.awt.Color(255, 255, 255));
        lblApostador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baccarat/icons/btn/icons8-pessoas-multiculturais-30.png"))); // NOI18N
        lblApostador.setText("Adicionar Apostador");
        lblApostador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblApostador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblApostador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblApostadorMouseClicked(evt);
            }
        });
        getContentPane().add(lblApostador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 220, 30));

        lblConfigJogo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblConfigJogo.setForeground(new java.awt.Color(255, 255, 255));
        lblConfigJogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baccarat/icons/btn/icons8-serviços-30.png"))); // NOI18N
        lblConfigJogo.setText("Configura Jogo");
        lblConfigJogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblConfigJogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblConfigJogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfigJogoMouseClicked(evt);
            }
        });
        getContentPane().add(lblConfigJogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 220, 30));

        lblConfigJogo1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblConfigJogo1.setForeground(new java.awt.Color(255, 255, 255));
        lblConfigJogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baccarat/icons/btn/icons8-locked-inside-30 (1).png"))); // NOI18N
        lblConfigJogo1.setText("Sair do Jogo");
        lblConfigJogo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblConfigJogo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblConfigJogo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfigJogo1MouseClicked(evt);
            }
        });
        getContentPane().add(lblConfigJogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 220, 30));

        lblApostador1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblApostador1.setForeground(new java.awt.Color(255, 255, 255));
        lblApostador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baccarat/icons/delete_32px.png"))); // NOI18N
        lblApostador1.setText("Limpar Jogo");
        lblApostador1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblApostador1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblApostador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblApostador1MouseClicked(evt);
            }
        });
        getContentPane().add(lblApostador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 220, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baccarat/icons/fundo_config.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 400));

        setSize(new java.awt.Dimension(277, 402));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblApostadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApostadorMouseClicked

        this.dispose();
        new AddApostadorView().setVisible(true);
        
    }//GEN-LAST:event_lblApostadorMouseClicked

    private void lblConfigJogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfigJogoMouseClicked
        // TODO add your handling code here:
        this.dispose();
        JFramesenha frm = new JFramesenha();
        frm.setVisible(true);
//        frm.toFront();
    }//GEN-LAST:event_lblConfigJogoMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void lblConfigJogo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfigJogo1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        this.parent.dispose();
        new splash().setVisible(true);
        
    }//GEN-LAST:event_lblConfigJogo1MouseClicked

    private void lblApostador1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApostador1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblApostador1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuJogoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuJogoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuJogoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuJogoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                menuJogoView dialog = new menuJogoView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblApostador;
    private javax.swing.JLabel lblApostador1;
    private javax.swing.JLabel lblConfigJogo;
    private javax.swing.JLabel lblConfigJogo1;
    // End of variables declaration//GEN-END:variables
}
